### ISSUE TITLE
User guide example

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#150]
User guide example for adding a person includes a criminal. Your target user is students. I doubt there are any students living in Newgate Prison who needs to meet his groupmates during his free time. He has no free time

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#25]</sub>

**Comment by elstonayx** [comment]
Thanks for spotting the error! We have made necessary changes.
