### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#151]
**Describe the bug**
Output error

**To Reproduce**
1. type edit 30 (with less than 30 persons in addressbook)
2. see suggestion : "At least one field to edit must be provided"

**Expected behavior**
I expected to see that the index does not exist

**Screenshots**

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#55]</sub>

**Comment by elstonayx** [comment]
same issue raised in #153
