### ISSUE TITLE
Edit phone number error

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#152]
**Describe the bug**

**To Reproduce**
1. key in 'edit 1 p/91234567546789765545678978675467897654 e/johndoe@example.com"
2. Error in side pane

**Expected behavior**
The full number should be displayed, but number is cut off

**Screenshots**

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#96]</sub>

**Comment by sylchw** [comment]
Shall we limit phone number to 8 numbers

**Comment by elstonayx** [comment]
yeah sure lets do that
