### ISSUE TITLE
Edit command exception 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#153]
**Describe the bug**
Edit command exception should report error invalid person index first

**To Reproduce**
1. edit command - "edit 100"

**Expected behavior**
Report invalid index number first 

**Screenshots**
![image](https://user-images.githubusercontent.com/35758553/47905861-047ba080-dec3-11e8-8a30-b8a9d300c7b5.png)

<hr>

**Reported by:** @pinjuen
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#121]</sub>

**Comment by elstonayx** [comment]
will be resolved in V2.0 as this is the original AB code
