### ISSUE TITLE
Functional error: Edit function works even when the edited parameter input is same as the old parameter

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#154]
When trying to edit a field, if the old field is keyed as the edited field, the edit command still works. User Guide, does not mention that the edit command should work even if the old field is typed in. This defeats the purpose of the edit function, as it works even when the parameters do not have any changes. 

**To Reproduce**
1. Go to edit 1 p/93210283
The edit should not work as the phone number entered is the same as the original phone number. 

**Screenshots**
![edit bug](https://user-images.githubusercontent.com/35731819/47908420-6946e480-de4a-11e8-9759-0d65fd27c903.PNG)

**Additional context**

<hr>

**Reported by:** @salsabiltasnia
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#187]</sub>

**Comment by sylchw** [comment]
It's the original addressbook code, should we change it? IMO it's not a game breaking flaw so it's not high severity

**Comment by elstonayx** [comment]
I don't think we will change this code as it does not really affect the application much. Closing this issue.
