### ISSUE TITLE
ExportAll (coming in v1.4) feature is listed in Command Summary section without the relevant tag

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#155]
**Describe the bug**
ExportAll is listed in [5. Command Summary] without the '(to be added)' tag.

**To Reproduce**
1. Key in "exportall csv" to in the Command Line
2. See error "Export failed!"

**Expected behavior**
The contact details of all persons is exported in csv format.

**Screenshots**
![screenshot 44](https://user-images.githubusercontent.com/42424678/47906432-34777380-dec4-11e8-8a8c-419005fa45a9.png)

**Additional context**
-

<hr>

**Reported by:** @darylnigel
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#233]</sub>

**Comment by elstonayx** [comment]
fixed in #200
