### ISSUE TITLE
Side pane information cut off

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#156]
**Please describe the problem**
The side pane information for schedule gets cut off

**Describe the improvement you'd like to suggest**
be able to expand side pane

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#247]</sub>

**Comment by linnnruoo** [comment]
I believe that this is a UI / fxml problem, i tried ```wrapText="true" ``` but it doesn seem to be working. Anyways all the panels have a minimum length, if the minimum length of other panels is not fulfilled, some panels cannot be stretched. I would say this bug should be rejected? Technically if the user has a wider screen, the use can drag to the maximum dimensions. Tho i dont find the excessive dragging part contributes to a good user experience

**Comment by linnnruoo** [comment]
@jitwei98 any comments?

**Comment by jitwei98** [comment]
For now, is it possible to extend the width of the leftmos pane without increasing the window size?

**Comment by linnnruoo** [comment]
@jitwei98  yup, resolved in #189  by setting the browser panel with no minimum width
