### ISSUE TITLE
Confusing info from user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#158]
**Describe the bug**
- schedule command said to be coming soon in V1.4 but it works in the product
- In user guide, command is stated as schedule in the title but in the example it is used as addschedule.

**Screenshots**
![image](https://user-images.githubusercontent.com/35758553/47906840-0ba3ae00-dec5-11e8-8d50-cc5520e246c4.png)

<hr>

**Reported by:** @pinjuen
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#322]</sub>

**Comment by elstonayx** [comment]
fixed in V1.4
