### ISSUE TITLE
If internet is off, select does not work

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#159]
**Describe the bug**
When internet is off, google api freezes

**To Reproduce**
1. turn off wifi
2. key in select 2
3. see error

**Expected behavior**
Expected an exception error t connect to the internet

**Screenshots**
![e2](https://user-images.githubusercontent.com/35603923/47906915-2bd36d00-dec5-11e8-8555-7ee0e75d1d78.JPG)

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#333]</sub>

**Comment by linnnruoo** [comment]
For the browser panel to work well, internet access is required. I dont think this is that severe. @jitwei98  what do you think?

**Comment by elstonayx** [comment]
I feel like this isn't that important to be fixed.

**Comment by sylchw** [comment]
Removed browser panel, replaced with calendar panel
