### ISSUE TITLE
Add Command accepts duplicate email, phone number, address and tags

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#160]
No two person ought to have the same phone number. 

**To Reproduce**
1. add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01
2. System adds the person
3. add n/David p/98765432 e/johnd@example.com a/John street, block 123, #01-01
4. System adds the person.

**Expected behavior**
There should be error handled stating that two people cannot have the same phone number. 2 people cannot be registered under the same phone number in real world.

<hr>

**Reported by:** @salsabiltasnia
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#358]</sub>

**Comment by elstonayx** [comment]
I think this isn't so big of an issue. The phone number doesn't necessarily mean mobile phone number. For instance, home numbers can be shared with multiple people, or fax numbers. Hence this shouldn't be an issue.
