### ISSUE TITLE
Visibility of schedule

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#161]
**Describe the bug**
The schedule is blocked and we can't see the whole thing.

**Expected behavior**
Whole schedule is visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/35758553/47907160-a3090100-dec5-11e8-8281-fae5b839b13e.png)

<hr>

**Reported by:** @pinjuen
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#377]</sub>

**Comment by linnnruoo** [comment]
similar issue to #156, its mainly caused by the length of other panels
