### ISSUE TITLE
Message error when listing empty book

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W12-1/main#162]
**Describe the bug**
After clearing address book, listing produces listed all persons message

**To Reproduce**
1. clear address book
2. list 
3. message "listed all persons" 

**Expected behavior**
Expected a "0 person listed" or "empty addressbook"

**Screenshots**
![e3](https://user-images.githubusercontent.com/35603923/47907321-009d4d80-dec6-11e8-84f7-a0b4ddf05c6d.JPG)

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#417]</sub>

**Comment by elstonayx** [comment]
This is the original addressbook code, and it makes sense saying that you list all persons available even if there aren't any persons in the addressbook.
