### ISSUE TITLE
Export feature does not work consistently

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#163]
**Describe the bug**
Export command gives the 'Export failed!' error, when example command is given.

**To Reproduce**
1. Type 'export 2 csv' in the Command Line and press 'Enter'
2. See error 'Export failed!'

**Expected behavior**
Contact details of person with INDEX 2 is exported in csv format.

**Screenshots**
![screenshot 45](https://user-images.githubusercontent.com/42424678/47907224-c469ed00-dec5-11e8-9546-a7ac4e485ef3.png)

**Additional context**
This command works on other occasions.

<hr>

**Reported by:** @darylnigel
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#421]</sub>

**Comment by elstonayx** [comment]
feature is removed and replaced with another feature in #200
