### ISSUE TITLE
I can export an empty addressbook

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#164]
**Describe the bug**
I can export an empty addressbook

**To Reproduce**
1. Clear addressbook
2. export csv

**Expected behavior**
Message "no contacts imported" or "cannot import contacts"

**Screenshots**
![e3](https://user-images.githubusercontent.com/35603923/47907594-87eac100-dec6-11e8-8171-de3f69d2b25e.JPG)

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#474]</sub>

**Comment by elstonayx** [comment]
fixed in #200
