### ISSUE TITLE
Introduction to the product

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#165]
**Describe the bug**
As stated in the intro of user guide, this product is for students who prefer to use a desktop app for managing contacts, email, and calendar. 
However, there is nothing I can do to the calendar and I cant see calendar anywhere on the product as well.

**Expected behavior**
Some function related to managing calendar.

<hr>

**Reported by:** @pinjuen
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#542]</sub>

**Comment by linnnruoo** [comment]
#189 #183 resolved
