### ISSUE TITLE
Message error for adding duplicate person

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#166]
**Describe the bug**
Message shows that i have added duplicate person successfully

**To Reproduce**
1. export 1 csv with the person already in the csv
2. see error

**Expected behavior**
A message telling me that person has already been added

**Screenshots**

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#557]</sub>

**Comment by elstonayx** [comment]
will be resolved in V2.0
