### ISSUE TITLE
Documentation error: Command works even though the User Guide claims it will only be included in v1.4

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#168]
**Describe the bug**
Documentation error: claims that "exportall vcf" will be in v1.4 but command is executable in v1.3

**To Reproduce**
1. exportall vcf
2. System shows message "Exported all contacts."

**Expected behavior**
The command ought not to be executable and should provide a message or error saying that the command is not ready yet. However, the command functions in this version.
Expected Message:
"Unknown command
No suggestions available."

<hr>

**Reported by:** @salsabiltasnia
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#653]</sub>

**Comment by elstonayx** [comment]
fixed in V1.4.
