### ISSUE TITLE
Confusing export command on user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#169]
**Describe the bug**
3.13 saying command that can export all contacts is coming in V1.4 but 3.12 shows a exportall command that can export all contacts?
Also, 3.13 saying that command to type is "export" and it shouldnt be working cuz it is coming in V1.4 but in 3.14 there's a command named same as "export"? This can be very confusing to users.

**Expected behavior**
State clearly what commands can be used and what can't.

**Screenshots**
![image](https://user-images.githubusercontent.com/35758553/47908354-0136e380-dec8-11e8-8716-249b3afe8020.png)

<hr>

**Reported by:** @pinjuen
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#677]</sub>

**Comment by elstonayx** [comment]
Issue is being solved currently

**Comment by jitwei98** [comment]
fixed in #210
