### ISSUE TITLE
Exit [parameters] will exit the app

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#170]
**Describe the bug**
as per title

**To Reproduce**
1. exit hello

**Expected behavior**
invalid command format

**Screenshots**

**Additional context**

<hr>

**Reported by:** @iamputradanish
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#681]</sub>

**Comment by linnnruoo** [comment]
Not accepted. ```exit``` is definitely executed first, so no matter what is typed after is ignored
