### ISSUE TITLE
Feedback on week 12 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-W12-1/main#178]
Subject: feedback on week 12 project progress

See [v1.4 progress guide](https://nuscs2113-ay1819s1.github.io/website/admin/project-w12-mid-v14.html) for more details of the activities mentioned below.

### Recommended progress for mid-v1.4

*  Milestone v1.4 _managed_ systematically
   - [x]  A suitable deadline set (:heavy_check_mark: well done!)
   - [x]  Issues allocated to it e.g., [link](https://github.com/CS2113-AY1819S1-W12-1/main/issues/13) (:heavy_check_mark: well done!)

### Recommended progress for mid-v1.4

- [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)
- [ ]  PPP available at `https://cs2113-ay1819s1-w12-1.github.io/main/team/linnnruoo.html` (:exclamation: try to do by next milestone)
- [ ]  PPP contains a link to your code on RepoSense (:exclamation: try to do by next milestone)

### Recommended progress for mid-v1.4

- [ ]  Has issues/PRs assigned for the milestone (:exclamation: try to do by next milestone)
- [ ]  PPP available at `https://cs2113-ay1819s1-w12-1.github.io/main/team/driedmelon.html` (:exclamation: try to do by next milestone)
- [ ]  PPP contains a link to your code on RepoSense (:exclamation: try to do by next milestone)

### Recommended progress for mid-v1.4

- [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)
- [x]  PPP available at `https://cs2113-ay1819s1-w12-1.github.io/main/team/elstonayx.html` (:heavy_check_mark: well done!)
- [ ]  PPP contains a link to your code on RepoSense (:exclamation: try to do by next milestone)

### Recommended progress for mid-v1.4

- [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)
- [x]  PPP available at `https://cs2113-ay1819s1-w12-1.github.io/main/team/jitwei98.html` (:heavy_check_mark: well done!)
- [ ]  PPP contains a link to your code on RepoSense (:exclamation: try to do by next milestone)

### Recommended progress for mid-v1.4

- [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)
- [ ]  PPP available at `https://cs2113-ay1819s1-w12-1.github.io/main/team/junweiljw.html` (:exclamation: try to do by next milestone)
- [ ]  PPP contains a link to your code on RepoSense (:exclamation: try to do by next milestone)

Tutor: @okkhoy

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2018-11-07 02:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.

**Comment by linnnruoo** [comment]
this needs to be updated asap

**Comment by jitwei98** [comment]
I updated my page with PR #179
