### ISSUE TITLE
Bug report - schedule command failure

### ISSUE THREAD

**Issue by linnnruoo** [CS2113-AY1819S1-W12-1/main#184]
![image](https://user-images.githubusercontent.com/32795221/48138675-c675e680-e2df-11e8-80b1-59cb3cde2bf0.png)
Reproduce the issue by typing the same command and its parameters.
Apparently it cant parse the dot ```.```

**Comment by sylchw** [comment]
thanks, will fix the bug

**Comment by sylchw** [comment]
should i include more than the dot, like other characters?

**Comment by sylchw** [comment]
Not gonna solve it's taking too much time

**Comment by sylchw** [comment]
I went to sleep, woke up and thought of the answer, it's done, will push via next pullrequest
