### ISSUE TITLE
Unable to get the edited content on DummySearchPage.html shown in the app

### ISSUE THREAD

**Issue by linnnruoo** [CS2113-AY1819S1-W12-1/main#51]
@jitwei98 can help me take a look into this? I wanted to edit the dummy content but it's not showing after it's rebuilt

**Comment by jitwei98** [comment]
You'll need to edit the link in seedu.address.ui.BrowserPanel.java #SEARCH_PAGE_URL.
Currently I still haven't figured out how to link it to local content yet.

**Comment by jitwei98** [comment]
Since @driedmelon already modified the BrowserPanel.java, I think this issue can be closed for now.
Feel free to reopen this issue if needed in the future.
